### ISSUE TITLE
Null exception from elmah error signal from context

### ISSUE THREAD

**Issue by paulgmiller** [creamdog/Nancy.Elmah#11]
Getting this on a nancy azure web site.
System.ArgumentNullException: Value cannot be null.
Parameter name: context
   at Elmah.ErrorSignal.FromContext(HttpContext context)
   at Nancy.Elmah.Elmahlogging.LogError(NancyContext context, Exception exception)
   at Nancy.ErrorPipeline.Invoke(NancyContext context, Exception ex)
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

Perhaps Logerror should do something like this 

        if (HttpContext.Current != null)//website is logging the error
        {                
            var elmahCon = Elmah.ErrorSignal.FromCurrentContext();
            elmahCon.Raise(ex);
        }
        else
        {                
            var elmahCon = Elmah.ErrorLog.GetDefault(null);
            elmahCon.Log(new Elmah.Error(ex));
        }
    }

Instead of just ErrorSignnal.FromConext().RaiseException().

Or maybe there's something else I'm missing.

**Comment by MisterY** [comment]
Not sure if this is the same but I'm getting

> {"Value cannot be null.\r\nParameter name: application"}	System.ArgumentNullException

on 

```
var signal = ErrorSignal.FromContext(context);
```
